name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  Action_Workflow:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Yarn & Percy CI
        uses: jpvalery/yarn-percy-ci@master
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
